# Default values for nodejs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.scontain.com:5050/enterjazz/temp-images
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "node-js"

imagePullSecrets:
  - name: sconeapps

scone:
  # If enabled, inject attestation information in
  # nodejs environment: SCONE_CAS_ADDR, SCONE_LAS_ADDR
  # and SCONE_CONFIG_ID.
  attestation:
    enabled: false
    lasUseHostIP: false
    las: 172.17.0.1
    cas: 4-2-1.scone-cas.cf
    ConfigID: NODE_SESSION-23261-30711-5522/app

  # Define any SCONE-related variables.
  env:
    - name: SCONE_MODE
      value: hw
    - name: SCONE_LOG
      value: "7"

useSGXDevPlugin: "scone"
#sgxEpcMem: 16

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nodejs
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
